// <auto-generated />
using Associations.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Associations.DataAccess.Migrations
{
    [DbContext(typeof(AssociationsDbContext))]
    [Migration("20190413171542_MigrateDB")]
    partial class MigrateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Associations.DataAccess.Entity.WordRels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("FemalePercents");

                    b.Property<int>("FemalePoints");

                    b.Property<float>("MalePercents");

                    b.Property<int>("MalePoints");

                    b.Property<float>("TotalPercents");

                    b.Property<int>("TotalPoints");

                    b.Property<int>("WordId");

                    b.Property<int>("WordRelId");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("WordRels");
                });

            modelBuilder.Entity("Associations.DataAccess.Entity.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Word");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Associations.DataAccess.Entity.WordRels", b =>
                {
                    b.HasOne("Associations.DataAccess.Entity.Words", "word")
                        .WithMany("Rels")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
