// <auto-generated />
using AssociationsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssociationsAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190326160133_Last")]
    partial class Last
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssociationsAPI.Models.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Word");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("AssociationsAPI.Models.WordsRel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FeMalePoints");

                    b.Property<int>("MalePoints");

                    b.Property<int>("TotalPoints");

                    b.Property<int>("WordId");

                    b.Property<int>("WordRelId");

                    b.HasKey("Id");

                    b.HasIndex("WordId")
                        .IsUnique();

                    b.HasIndex("WordRelId")
                        .IsUnique();

                    b.ToTable("WordsRels");
                });

            modelBuilder.Entity("AssociationsAPI.Models.WordsRel", b =>
                {
                    b.HasOne("AssociationsAPI.Models.Words", "Word")
                        .WithOne("MainWordsRel")
                        .HasForeignKey("AssociationsAPI.Models.WordsRel", "WordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssociationsAPI.Models.Words", "AssociativeWord")
                        .WithOne("WordsRel")
                        .HasForeignKey("AssociationsAPI.Models.WordsRel", "WordRelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
